### ISSUE TITLE
use "#cds-models" in the examples

### ISSUE THREAD

**Issue by corey-aloia** [dxfrontier/cds-ts-samples#28]
Would it make sense to use `import {} from '#cds-models/'` in the examples? 

For example:
```
import { UserActivityLog } from '#cds-models/AdminService';
```
instead of
```
import { UserActivityLog } from '../../../../@cds-models/AdminService';
```

And, BTW, does this also work with cds files? So could we add a path for the "db" folder instead of adding a bunch of '..' and trying to find it? This also makese refactoring/moving our files around easier :) 

Thanks!

**Comment by corey-aloia** [comment]
If you think this makes sense, then here is a PR for this:
https://github.com/dxfrontier/cds-ts-samples/pull/29/files

**Comment by hakimio** [comment]
`#cds-models` path alias works because it's defined in [`tsconfig`](https://github.com/dxfrontier/cds-ts-samples/blob/cd60f584ddc81c8a4d5dd37c7d7347ab45efb3d5/tsconfig.json#L28C7-L28C52) and [`package.json`](https://github.com/dxfrontier/cds-ts-samples/blob/cd60f584ddc81c8a4d5dd37c7d7347ab45efb3d5/package.json#L49). Those kind of aliases will not work in `cds` schemas.

**Comment by dragolea** [comment]
@corey-aloia I've merged your proposals, but I need to check what happens when the `mbt built` is triggered, as mbt build will transpile TS to JS ... 

Have you checked this case ?

**Comment by dragolea** [comment]
This looks all right for the moment.
Thanks @corey-aloia

**Comment by corey-aloia** [comment]
Cool 👍 

And actually, I was also wondering why `#` instead of `@` in the tsconfig :) 
I.E. `import { UserActivityLog } from '@cds-models/AdminService';`

**Comment by dragolea** [comment]
This is how `cds-typer` from SAP handles this import, when you do`npm add typer` 

Have a look over SAP npm package, https://github.com/cap-js/cds-typer you can also suggest that, as it would make more sense instead of `#`

**Comment by hakimio** [comment]
It's to distinguish between your own path aliases and 3rd party library imports.

> Entries in the imports field must start with the # symbol. This ensures that they are distinguished from package specifiers like @. 

[source](https://betterprogramming.pub/the-native-way-to-configure-path-aliases-in-frontend-projects-5db70f19a6e0#38de:~:text=Starting%20from%20the%20setup%20phase%2C%20we%20face%20the%20first%20limitation%3A%20entries%20in%20the%20imports%20field%20must%20start%20with%20the%20%23%20symbol.%20This%20ensures%20that%20they%20are%20distinguished%20from%20package%20specifiers%20like%20%40.)

If you used [yarn workspaces](https://yarnpkg.com/features/workspaces) or some mono-repo tool like [Nrwl Nx](https://nx.dev/), you could also prefix your internal libraries with your organization name like `@my-org/models`.
